defaults: 
  - submitit_slurm
  
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 500
partition: booster
account: hai_dm4eo
nodes: 1
tasks_per_node: 4
cpus_per_task: 12
gpus_per_task: 1
gres: gpu:4
